using Lumen.Domain;

namespace Lumen.Analysis.Tests;

public sealed class MechanicalClassifierTests
{
    [Theory]
    [InlineData("src/Data/Migrations/20240101120000_AddInvoices.cs", "Database migration")]
    [InlineData("src/Data/migrations/20240101120000_AddInvoices.cs", "Database migration")]
    [InlineData("src/Data/Migrations/AppDbContextModelSnapshot.cs", "Generated code")]
    [InlineData("src/Forms/MainForm.Designer.cs", "Generated code")]
    [InlineData("src/Forms/MainForm.designer.cs", "Generated code")]
    [InlineData("src/Api/Client.g.cs", "Generated code")]
    [InlineData("src/Api/Client.generated.cs", "Generated code")]
    [InlineData("src/App/packages.lock.json", "Lock file")]
    [InlineData("web/package-lock.json", "Lock file")]
    [InlineData("web/yarn.lock", "Lock file")]
    [InlineData("web/pnpm-lock.yaml", "Lock file")]
    [InlineData("go.sum", "Lock file")]
    [InlineData("web/Package-Lock.json", "Lock file")]
    public void ClassifiesMechanicalPaths(string path, string reason)
    {
        var result = MechanicalClassifier.Classify(path, []);

        Assert.True(result.IsMechanical);
        Assert.Equal(reason, result.Reason);
    }

    [Theory]
    [InlineData("src/Workers/InvoiceRetryWorker.cs")]
    [InlineData("src/Migrations/README.md")]
    [InlineData("src/MigrationsHelper/Thing.cs")]
    [InlineData("src/Designer.cs")]
    [InlineData("package.json")]
    public void LeavesNormalFilesAlone(string path)
    {
        Assert.Equal(MechanicalClassification.None, MechanicalClassifier.Classify(path, []));
    }

    [Fact]
    public void DetectsAutoGeneratedHeaderInTheFirstLines()
    {
        var hunks = ChangedFiles.FromUnifiedDiff(
            Support.TestDiffs.AddedFile("src/Api/Client.cs", "// <auto-generated>\n//   by a tool\n// </auto-generated>\nclass C { }"))[0].Hunks;

        var result = MechanicalClassifier.Classify("src/Api/Client.cs", hunks);

        Assert.Equal(new MechanicalClassification(true, "Generated code"), result);
    }

    [Fact]
    public void IgnoresAutoGeneratedMarkerFarDownTheFile()
    {
        var text = string.Join('\n', Enumerable.Range(0, 30).Select(i => $"// line {i}")) + "\n// <auto-generated>";
        var hunks = ChangedFiles.FromUnifiedDiff(Support.TestDiffs.AddedFile("src/Api/Client.cs", text))[0].Hunks;

        Assert.False(MechanicalClassifier.Classify("src/Api/Client.cs", hunks).IsMechanical);
    }

    [Fact]
    public void ChangedFilesAppliesClassificationAndSortsByPath()
    {
        var diff =
            Support.TestDiffs.AddedFile("src/Z.cs", "class Z { }") +
            Support.TestDiffs.AddedFile("src/Data/Migrations/1_Init.cs", "class Init { }") +
            Support.TestDiffs.AddedFile("src/A.cs", "class A { }");

        var files = ChangedFiles.FromUnifiedDiff(diff);

        Assert.Equal(["src/A.cs", "src/Data/Migrations/1_Init.cs", "src/Z.cs"], files.Select(f => f.Path));
        Assert.Equal([false, true, false], files.Select(f => f.Mechanical.IsMechanical));
        Assert.All(files, f => Assert.Equal(1, f.Additions));
    }
}
