using Lumen.Domain;

namespace Lumen.Analysis;

/// <summary>
/// Recognises changes that rarely deserve human judgement (generated code, migrations, lock files) so the
/// UI can collapse them and detectors can skip them.
/// </summary>
public static class MechanicalClassifier
{
    /// <summary>The built-in rules, in words, for the Settings panel.</summary>
    public static readonly IReadOnlyList<string> BuiltInDescriptions =
    [
        "*.Designer.cs", "*.g.cs", "*.generated.cs", "*ModelSnapshot.cs", "Migrations/*.cs", "lock files", "<auto-generated> headers",
    ];

    private static readonly string[] GeneratedSuffixes =
    [
        ".Designer.cs", ".designer.cs", ".g.cs", ".g.i.cs", ".generated.cs", "ModelSnapshot.cs",
    ];

    private static readonly string[] LockFiles =
    [
        "packages.lock.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Cargo.lock", "poetry.lock", "go.sum",
    ];

    /// <param name="extraPatterns">The repository's own mechanical path patterns (see <see cref="PathPattern"/>).</param>
    public static MechanicalClassification Classify(string path, IReadOnlyList<DiffHunk> hunks, IReadOnlyList<string>? extraPatterns = null)
    {
        var fileName = Path.GetFileName(path);

        if (extraPatterns is { Count: > 0 } && PathPattern.MatchesAny(extraPatterns, path))
        {
            return new(true, "Marked mechanical in settings");
        }

        if (LockFiles.Contains(fileName, StringComparer.OrdinalIgnoreCase))
        {
            return new(true, "Lock file");
        }

        if (GeneratedSuffixes.Any(s => fileName.EndsWith(s, StringComparison.Ordinal)))
        {
            return new(true, "Generated code");
        }

        var segments = path.Split('/');
        if (segments.Any(s => s.Equals("Migrations", StringComparison.OrdinalIgnoreCase)) &&
            path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            return new(true, "Database migration");
        }

        if (hunks.SelectMany(h => h.Lines).Take(20).Any(l => l.Text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)))
        {
            return new(true, "Generated code");
        }

        return MechanicalClassification.None;
    }
}
